### ISSUE TITLE
error with exakat 2.1.0 - missing groovy-2.5.7-indy.jar

### ISSUE THREAD

**Issue by rcampbel3** [exakat/exakat#135]
Hi,

This was working around exakat 2.0.5 in this same repository. Here's the error I'm getting:

wants groovy-2.5.7-indy.jar
NOTE: In tinkergraph/lib/ there is only groovy-2.4.16-indy.jar
in tinkergraph.old/lib (from 2.0.X install) there is groovy-2.5.7-indy.jar
I've manually copied it over and am trying again.

Do I need to regenerate my projects when versions change?

```
 # php ./exakat project -p apps
                                                                                                                                                                         
Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : startup
 failed:
IO Exception attempting to load global transforms:/data/tinkergraph/lib/groovy-2.5.7-indy.jar (No such file or directory)
                                                             
1 error                      
                                                                                 
                             
 ===================  SERVER TRACE  =========================
array (                 
  'stackTrace' => 'org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
IO Exception attempting to load global transforms:/data/tinkergraph/lib/groovy-2.5.7-indy.jar (No such file or directory)

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
        at org.codehaus.groovy.control.ProcessingUnit.completePhase(ProcessingUnit.java:147)
        at org.codehaus.groovy.control.ProcessingUnit.gotoPhase(ProcessingUnit.java:166)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:590)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
        at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
        at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
        at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:309)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:251)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.lambda$load$0(GremlinGroovyScriptEngine.java:819)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604)
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.load(GremlinGroovyScriptEngine.java:817)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$GroovyCacheLoader.load(GremlinGroovyScriptEngine.java:812)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3117)
        at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:144)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$16(BoundedLocalCache.java:1968)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1966)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1949)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.getScriptClass(GremlinGroovyScriptEngine.java:567)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:374)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
',
  'exceptions' =>
  array (
    0 => 'org.codehaus.groovy.control.MultipleCompilationErrorsException',
  ),
)
 ============================================================

on file phar:///data/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 847
```

**Comment by dseguy** [comment]
Hi rcampbel3

This looks like an installation problem in the tinkergraph server, indeed. I have 35 different files in tinkergraph/lib, so you might be missing some of them. 

My suggestion is to reinstall the tinkergraph server. 
1) Kill the running tinkergraph
2) rename the current tinkergraph folder 
3) run `php exakat.phar install -v`(this checks for zip, java, and run an automated script to install tinkergraph; Otherwise, use the documentation for manual installation). 
4) Run the audit again.

Note that tinkergraph is only need when running the audit, and not when extracting reports. That will not affect your current results.

**Comment by rcampbel3** [comment]
Thanks for the suggestions.

php exakat.phar install -v did not download and create a new tinkergraph directory. It does do a bunch of other stuff that I can see from running strace on it.

I killed tinkergraph, used my new directory with groovy-2.5.7-indy.jar, re-ran in this problem repository and got the following:

```
 php ./exakat project -p apps
         
Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : The pro
vided traverser does not map to a value: v[493418]->[Neo4jGraphStep(vertex,[493437])]
 
 ===================  SERVER TRACE  =========================
array (
  'stackTrace' => 'java.lang.IllegalArgumentException: The provided traverser does not map to a value: v[493418]->[Neo4jGraphStep(vertex,[493437])]
        at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.apply(TraversalUtil.java:45)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.Parameters.get(Parameters.java:92)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.AddEdgeStep.map(AddEdgeStep.java:101)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.AddEdgeStep.map(AddEdgeStep.java:50)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:37)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
        at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
        at org.apache.tinkerpop.gremlin.process.traversal.Traversal.iterate(Traversal.java:203)
        at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal.iterate(GraphTraversal.java:2704)
        at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin.iterate(GraphTraversal.java:179)
        at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.iterate(DefaultGraphTraversal.java:48)
        at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin$iterate.call(Unknown Source)
        at Script4$_run_closure1.doCall(Script4.groovy:4)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:420)
        at groovy.lang.Closure.call(Closure.java:436)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForLine(DefaultGroovyMethods.java:5371)
        at org.codehaus.groovy.runtime.IOGroovyMethods.eachLine(IOGroovyMethods.java:487)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachLine(ResourceGroovyMethods.java:296)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachLine(ResourceGroovyMethods.java:262)
        at org.codehaus.groovy.runtime.dgm$943.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at Script4.run(Script4.groovy:1)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:684)
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:386)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
',
  'exceptions' =>
  array (
    0 => 'java.lang.IllegalArgumentException',
  ),
)
 ============================================================

on file phar:///data/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 847
```

Here's output of 'exakat doctor'

```
# php exakat doctor       
exakat :                        
    executable           : exakat           
    version              : 2.1.0
    build                : 1068
    exakat.ini           : ./config/exakat.ini  
    graphdb              : gsneo4j
    reports              :    
    rulesets             : CompatibilityPHP70,
                           CompatibilityPHP71,
                           CompatibilityPHP72,
                           CompatibilityPHP73,
                           Analyze,
                           Preferences,
                           Appinfo,
                           Appcontent,
                           "Dead code",
                           Security,
                           Custom,
                           Stats
    extra rulesets       :
    tokenslimit          : 1 000 000 000

PHP :
    binary               : 7.4.6
    memory_limit         : -1
    short_open_tags      : Off
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes
    ext/xmlwriter        : Yes
    ext/pcntl            : Yes
    xdebug.max_nesting_l : 1001 (Must be -1 or more than 1000)
    parallel_processing  : Yes
    pcre.jit             : On (Must be off on PHP 7.3 and OSX)

java :
    installed            : Yes
    type                 : OpenJDK Runtime Environment Corretto-8.212.04.1 (build 1.8.0_212-b04)
    version              : openjdk
    $JAVA_HOME           : <none>
    $JAVA_OPTIONS        :

tinkergraph :
    installed            : No (folder : tinkergraph)

gsneo4j :
    installed            : Yes (folder : /data/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182                                                                                                                                                                              
    gremlin version      : 3.3.6                                                                                                                                                                             
    neo4j version        : 3.2.3

project :
    name                 :
    url                  :
    phpversion           : 7.4
    reports              : "Ambassador"
    rulesets             : CompatibilityPHP70, CompatibilityPHP71, CompatibilityPHP72, CompatibilityPHP73, Analyze, Preferences, Appinfo, Appcontent, "Dead code", Security, Custom, Stats
    included dirs        :
    ignored dirs         : /assets, /cache, /css, /data, /doc, /docker, /docs, /example, /examples, /images, /js, /lang, /spec, /sql, /test, /tests, /tmp, /version, /var
    file extensions      : php, php3, inc, tpl, phtml, tmpl, phps, ctp, module

folders :
    projects folder      : Yes
    projects/test        : No
    projects/default     : No
    projects/onepage     : No

php52 :
    configured           : No

php53 :
    configured           : No

php54 :
    configured           : No

php55 :
    configured           : No

php56 :
    configured           : Yes (/usr/bin/php5.6)
    actual version       : 5.6.40

php70 :
    configured           : Yes (/usr/bin/php7.0)
    actual version       : 7.0.33

php71 :
    configured           : Yes (/usr/bin/php7.1)
    actual version       : 7.1.33

php72 :
    configured           : Yes (/usr/bin/php7.2)
    actual version       : 7.2.31

php73 :
    configured           : Yes (/usr/bin/php7.3)
    actual version       : 7.3.18

php74 :
    configured           : Yes (/usr/bin/php7.4)
    actual version       : 7.4.6
    auditing             : with this version

php80 :
    configured           : Yes (/usr/bin/php8.0)
    actual version       : 8.0.0
```

**Comment by exakat** [comment]
Now, this is going to be an internal error that you ran into. The best is going to update to the current version 2.1.3 (https://exakat.readthedocs.io/en/latest/Commands.html#update), or even the upcoming 2.1.4. 

If the code is accessible, it will help (but not necessary).
