### ISSUE TITLE
Docker image exakat latest is failing with : gremlin-groovy is not an available GremlinScriptEngine

### ISSUE THREAD

**Issue by maxerbox** [exakat/exakat#136]
Here are my logs :
``` 
Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : gremlin-groovy is not an available GremlinScriptEngine
===================  SERVER TRACE  ========================= 
array (
  'stackTrace' => 'java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.registerLookUpInfo(CachedGremlinScriptEngineManager.java:95)
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:58)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:267)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
',
  'exceptions' => 
  array (
    0 => 'java.lang.IllegalArgumentException',
  ),
)
 ============================================================ 
 
on file phar:///usr/src/exakat/exakat/vendor/brightzone/gremlin-php/src/Connection.php
on line 847
```

**Comment by maxerbox** [comment]
Move at https://github.com/exakat/exakat-docker/issues/20
