### ISSUE TITLE
Error on MacOS Monterey 12.1 - gremlin-groovy is not an available GremlinScriptEngine

### ISSUE THREAD

**Issue by itbecomesfluid** [exakat/exakat#155]
Hi,

I'm trying to get Exakat running on macOS Monterey 12.1.

I installed PHP and Java via homebrew as they aren't available as part of the OS.

I then installed as follows:

```php exakat.pair install``` returned:
```Java : OK
Zip : OK
Starting download of tinkergraph.
Gremlin server checksum OK
Tinkergraph installed
Starting download of tinkergraph plugin Neo4j.
Neo4j for Tinkergraph installed

Warning: mkdir(): phar error: cannot create directory "phar:///Users/user/Desktop/exakat-new/exakat.phar/stubs", write operations disabled in phar:///Users/user/Desktop/exakat-new/exakat.phar/library/Exakat/Tasks/Doctor.php on line 250
exakat : 
    executable           : exakat.phar
    version              : 2.3.0
    build                : 1265
    exakat.ini           : ./config/exakat.ini
    graphdb              : gsneo4jv3
    reports              : 
    rulesets             : CompatibilityPHP74,
                           CompatibilityPHP80,
                           CompatibilityPHP81,
                           Analyze,
                           Appinfo
    extra rulesets       : 
    ignored rules        : 
    tokenslimit          : 1 000 000 000
    stubs                : 

PHP : 
    binary               : 8.1.1
    memory_limit         : 128M
    short_open_tags      : Off
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes
    ext/xmlwriter        : Yes
    pcre.jit             : On (Must be off on PHP 7.3 and OSX)

java : 
    installed            : Yes
    type                 : OpenJDK Runtime Environment Homebrew (build 17.0.1+1)
    version              : openjdk
    $JAVA_HOME           : <none>
    $JAVA_OPTIONS        : 

tinkergraph : 
    installed            : Yes (folder : /Users/user/Desktop/exakat-new/tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.4.12

tinkergraphv3 : 
    installed            : Yes (folder : /Users/user/Desktop/exakat-new/tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.4.12

gsneo4j : 
    installed            : No (folder : tinkergraph)

gsneo4jv3 : 
    installed            : Yes (folder : /Users/user/Desktop/exakat-new/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182
    gremlin version      : 3.4.12
    neo4j version        : 3.2.3

nogremlin : 
    installed            : Always

project : 
    name                 : 
    url                  : 
    phpversion           : 81
    reports              : "Diplomat"
    rulesets             : CompatibilityPHP74, CompatibilityPHP80, CompatibilityPHP81, Analyze, Appinfo
    included dirs        : 
    ignored dirs         : /assets, /cache, /css, /data, /doc, /docker, /docs, /example, /examples, /images, /js, /lang, /spec, /sql, /test, /tests, /tmp, /version, /var
    ignored rules        : 
    file extensions      : php, php3, inc, tpl, phtml, tmpl, phps, ctp, module

folders : 
    projects folder      : Yes

php81 : 
    configured           : Yes (/usr/local/Cellar/php/8.1.1/bin/php)
    actual version       : 8.1.1
```

I then initialised a new project:

```php exakat.phar init -p itbfcrm```

which produced no output

And then attempted to run a report:

```php exakat.phar project -p itbfcrm```

which generated the following error:

```Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : gremlin-groovy is not an available GremlinScriptEngine

 ===================  SERVER TRACE  ========================= 
array (
  'stackTrace' => 'java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.registerLookUpInfo(CachedGremlinScriptEngineManager.java:95)
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:58)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
',
  'exceptions' => 
  array (
    0 => 'java.lang.IllegalArgumentException',
  ),
)
 ============================================================ 
 
on file phar:///Users/user/Desktop/exakat-new/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 847
```

I'm unsure how to resolve this.  Please help.  Thanks.

**Comment by exakat** [comment]
Hi @itbecomesfluid 

The Java version is possibly the problem here. Locally, it is tested on 1.8.x, from Oracle. 
I am trying to find a recommendation for java version to gremlin. It might not go to 17 though.

I suggest you try to install java 8 instead.

**Comment by exakat** [comment]
Java 8 or 11 are the recommended version for gremlin, hence for exakat too.

**Comment by itbecomesfluid** [comment]
Changing to Java 11 fixed it.  Many thanks for the advice.
