### ISSUE TITLE
Is there a way to include composer packages for class resolving?

### ISSUE THREAD

**Issue by donis** [exakat/exakat#31]
If I run exakat on a project that has heavy composer dependencies, I get tons of `Undefined Classes` and related issues counted, which is actually not true. Am I missing some configuration option or so?

**Comment by mdemori** [comment]
Hi, I'm trying exakat under windows WSL with a very old procedural project (php 5.x) currently i use PHP 7.2 as engine. The process stop almost immediatly with a java exception. How can I fix this problem? below the error with stack trace.

```
Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : Expected an id that is convertible to Long but received class org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource

 ===================  SERVER TRACE  =========================
array (
  '@type' => 'g:Map',
  '@value' =>
  array (
    0 => 'stackTrace',
    1 => 'java.lang.IllegalArgumentException: Expected an id that is convertible to Long but received class org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource
        at org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$DefaultIdManager$1.convert(TinkerGraph.java:587)
        at org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.lambda$createElementIterator$4(TinkerGraph.java:316)
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils$3.next(IteratorUtils.java:247)
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils$4.advance(IteratorUtils.java:299)
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils$4.hasNext(IteratorUtils.java:269)
        at org.apache.tinkerpop.gremlin.tinkergraph.process.traversal.step.sideEffect.TinkerGraphStep.iteratorList(TinkerGraphStep.java:114)
        at org.apache.tinkerpop.gremlin.tinkergraph.process.traversal.step.sideEffect.TinkerGraphStep.vertices(TinkerGraphStep.java:85)
        at org.apache.tinkerpop.gremlin.tinkergraph.process.traversal.step.sideEffect.TinkerGraphStep.lambda$new$0(TinkerGraphStep.java:59)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:142)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:200)
        at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.apply(TraversalUtil.java:43)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.Parameters.get(Parameters.java:92)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.AddEdgeStep.map(AddEdgeStep.java:102)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.AddEdgeStep.map(AddEdgeStep.java:50)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:37)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
        at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.handleIterator(AbstractOpProcessor.java:89)
        at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.lambda$evalOpInternal$5(AbstractEvalOpProcessor.java:252)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:274)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
',
    2 => 'exceptions',
    3 =>
    array (
      '@type' => 'g:List',
      '@value' =>
      array (
        0 => 'java.lang.IllegalArgumentException',
      ),
    ),
  ),
)
 ============================================================

on file phar:///test/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 829
```
