### ISSUE TITLE
Get error "No such property: graph for class: Script3"

### ISSUE THREAD

**Issue by mdll** [exakat/exakat#59]
I installed exakat on Ubuntu 16.04 by using the documentation on exakat.readthedocs.io and get the following error message:

# php exakat.phar project -p sculpin

Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : No such property: graph for class: Script3

 ===================  SERVER TRACE  ========================= 
array (
  'stackTrace' => 'groovy.lang.MissingPropertyException: No such property: graph for class: Script3
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
	at Script3.run(Script3.groovy:1)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:856)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:561)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
	at org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines.eval(ScriptEngines.java:135)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:291)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
',
  'exceptions' => 
  array (
    0 => 'groovy.lang.MissingPropertyException',
  ),
)
 ============================================================ 
 
on file phar:///var/www/in.hoppl.staticanalysis/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 829

**Comment by exakat** [comment]
Can you check if Gremlin-server 3.2.9 (or any 3.2.x) is the tinkergraph version ? 

So, Exakat is trying to connect to the graph server, and succeed, but cannot find the 'g' variable, which is default with gremlin-server. I suspect something is missing in the gremlin-server installation, though I can't really see what it could be. 

It won't work on 3.3.x yet, and probably doesn't work on 3.1- anymore.

**Comment by nikossvnk** [comment]
I was getting the same error and by inspecting the gremlin log file I saw that the "real" error was that it couldn't start the server at port 8182. Check if a java server is already running at this port and stop/restart it

**Comment by exakat** [comment]
Another option is that the installation of Neo4j in Gremlin server failed silently. 

The error is a temporary network error, easy to miss as the process doesn't fails, but keeps going on, even partially installed.

```
[INFO] DependencyGrabber$_copyTo_closure6 - Copying - /tinkergraph/bin/ext/neo4j-gremlin/plugin/neo4j-tinkerpop-api-0.1.jar
Could not install the dependency: java.lang.RuntimeException: Error grabbing Grapes -- [download failed: com.hazelcast#hazelcast-all;3.7.5!hazelcast-all.jar]
java.lang.RuntimeException: java.lang.RuntimeException: Error grabbing Grapes -- [download failed: com.hazelcast#hazelcast-all;3.7.5!hazelcast-all.jar]
````

The only solution is then to remove the tinkergraph folder, and try the installation again.

**Comment by girishi** [comment]
Hi , getting similar issue as shown below, unable to proceed , please suggest how to overcome

Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : Vertex with id already exists: 1
array (
  '@type' => 'g:Map',
  '@value' => 
  array (
    0 => 'stackTrace',
    1 => 'java.lang.IllegalArgumentException: Vertex with id already exists: 1
	at org.apache.tinkerpop.gremlin.structure.Graph$Exceptions.vertexWithIdAlreadyExists(Graph.java:1137)
	at org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.addVertex(TinkerGraph.java:167)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.createVertex(Attachable.java:291)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.lambda$create$10(Attachable.java:149)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable.attach(Attachable.java:63)
	at org.ap



------------
and the config of tinkergraph is shown as below , is it because of any version mismatch
tinkergraph : 
    installed            : Yes (folder : tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.3.3

gsneo4j : 
    installed            : Yes (folder : /root/exakat/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182
    gremlin version      : 3.3.3
    neo4j version        : 3.2.3
