### ISSUE TITLE
Error when running 'php exakat.phar project -p sculpin' following the tutorial

### ISSUE THREAD

**Issue by sh4ka** [exakat/exakat#72]
Hello, I get this error when running the instructions from the tutorial. I've been looking through past and present issues and I haven't found any solution.
My configuration is the one supplied at installation time.

```
Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : gremlin-groovy is not an available GremlinScriptEngine

 ===================  SERVER TRACE  =========================
array (
  'stackTrace' => 'java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine
        at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.registerLookUpInfo(CachedGremlinScriptEngineManager.java:95)
        at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:58)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:263)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
',
  'exceptions' =>
  array (
    0 => 'java.lang.IllegalArgumentException',
  ),
)
 ============================================================

on file phar:///var/data/home/jesus.flores/exacat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 849
```

**Comment by girishi** [comment]
Hi , getting similar issue as shown below, unable to proceed , please suggest how to overcome

Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : Vertex with id already exists: 1
array (
  '@type' => 'g:Map',
  '@value' => 
  array (
    0 => 'stackTrace',
    1 => 'java.lang.IllegalArgumentException: Vertex with id already exists: 1
	at org.apache.tinkerpop.gremlin.structure.Graph$Exceptions.vertexWithIdAlreadyExists(Graph.java:1137)
	at org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.addVertex(TinkerGraph.java:167)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.createVertex(Attachable.java:291)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.lambda$create$10(Attachable.java:149)
	at org.apache.tinkerpop.gremlin.structure.util.Attachable.attach(Attachable.java:63)
	at org.ap



------------
and the config of tinkergraph is shown as below , is it because of any version mismatch
tinkergraph : 
    installed            : Yes (folder : tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.3.3

gsneo4j : 
    installed            : Yes (folder : /root/exakat/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182
    gremlin version      : 3.3.3
    neo4j version        : 3.2.3

**Comment by girishi** [comment]
> Hi , getting similar issue as shown below, unable to proceed , please suggest how to overcome
> 
> Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : Vertex with id already exists: 1
> array (
> '@type' => 'g:Map',
> '@value' =>
> array (
> 0 => 'stackTrace',
> 1 => 'java.lang.IllegalArgumentException: Vertex with id already exists: 1
> at org.apache.tinkerpop.gremlin.structure.Graph$Exceptions.vertexWithIdAlreadyExists(Graph.java:1137)
> at org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.addVertex(TinkerGraph.java:167)
> at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.createVertex(Attachable.java:291)
> at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.lambda$create$10(Attachable.java:149)
> at org.apache.tinkerpop.gremlin.structure.util.Attachable.attach(Attachable.java:63)
> at org.ap
> 
> and the config of tinkergraph is shown as below , is it because of any version mismatch
> tinkergraph :
> installed : Yes (folder : tinkergraph)
> host : 127.0.0.1
> port : 7474
> gremlin version : 3.3.3
> 
> gsneo4j :
> installed : Yes (folder : /root/exakat/tinkergraph)
> host : 127.0.0.1
> port : 8182
> gremlin version : 3.3.3
> neo4j version : 3.2.3

solution-
This issue could be solved by killing the tinkergraph process and running the command to generate reports gave the results and it worked fine.

**Comment by exakat** [comment]
Could you test this with a current version? as of today, 1.9.4
