### ISSUE TITLE
Unable to generate Ambassador report

### ISSUE THREAD

**Issue by ltribolet** [exakat/exakat#74]
Running into in issue either after running `report` or `project` commands:

```
[19-Sep-2018 16:48:15 UTC] PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, no such table: cit in phar:///Volumes/Dev/exakat/exakat.phar/library/Exakat/Reports/Ambassador.php on line 2815
``` 

And this is the end of `project` command output (let me know if you need more):
```
Running the following themes : Inventory, Analyze, Appinfo, Security, CompatibilityPHP54, CompatibilityPHP55, CompatibilityPHP56, Performances, Appcontent, Dead code, CompatibilityPHP53, Custom, CompatibilityPHP70, CompatibilityPHP71, CompatibilityPHP72, Preferences, CompatibilityPHP73, Suggestions, ClassReview
27/27 [=========================================================================================================================================>] 100.00% 00:00:00
357/357 [=======================================================================================================================================>] 100.00% 00:00:00
339/339 [===============================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
38/38 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
70/70 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
62/62 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
51/51 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
37/37 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
36/36 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
25/25 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
74/74 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
2/2 [===================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
45/45 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
30/30 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
22/22 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
27/27 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
8/8 [===================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
63/63 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
12/12 [=================================================================================================================================================================================================================================================================================>] 100.00% 00:00:00
Analyzed project
Reporting Ambassador
Building report for project professional in "report", with format Ambassador
Error while building Ambassador in Ambassador.
Reported project
End
```

I checked both `dump.sqlite` and `datastore.sqlite` and indeed there is no table like that.
```
sqlite> .databases
main: /Volumes/Dev/exakat/projects/project1/datastore.sqlite
sqlite> .tables
analyzed           dictionary         hash               tokenCounts
compilation71      externallibraries  hashAnalyzer
composer           files              ignoredFiles
configFiles        functioncalls      shortopentag
```
```
sqlite> .databases
main: /Volumes/Dev/exakat/projects/project1/dump.sqlite
sqlite> .tables
analyzed           externallibraries  hashResults        shortopentag
compilation71      files              ignoredFiles       themas
composer           hash               results            tokenCounts
configFiles        hashAnalyzer       resultsCounts
```

Other reports can be generated fine (the few I tested anyway).

```
php exakat.phar doctor -p project1
exakat :
    executable           : exakat.phar
    version              : 1.4.3
    build                : 813
    exakat.ini           : config/exakat.ini,
                           project1/config.ini
    graphdb              : gsneo4j
    reports              : Ambassador
    themes               : CompatibilityPHP70,
                           CompatibilityPHP71,
                           CompatibilityPHP72,
                           Dead code,
                           Security
    extra themes         :
    tokenslimit          : 1 000 000 000

PHP :
    binary               : 7.1.21
    memory_limit         : 128M
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes
    ext/xmlwriter        : Yes

java :
    installed            : Yes
    type                 : Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
    version              : java
    $JAVA_HOME           : /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
    $JAVA_OPTIONS        : -Xms1024m -Xmx2048m

tinkergraph :
    installed            : Yes (folder : tinkergraph)
    host                 : 127.0.0.1
    port                 : 7474
    gremlin version      : 3.3.3

gsneo4j :
    installed            : Yes (folder : /Volumes/Dev/exakat/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182
    gremlin version      : 3.3.3
    neo4j version        : 3.2.3

project :
    name                 :
    url                  :
    included dirs        : /app
    ignored dirs         : /
    file extensions      : php, php3, inc, tpl, phtml, tmpl, phps, ctp, module
    analyzers            :

folders :
    projects folder      : Yes
    projects/test        : No
    projects/default     : No
    projects/onepage     : No

php52 :
    configured           : No

php53 :
    configured           : No

php54 :
    configured           : No

php55 :
    configured           : No

php56 :
    configured           : No

php70 :
    configured           : No

php71 :
    configured           : Yes (/usr/local/Cellar/php@7.1/7.1.21/bin/php)
    version              : 7.1.21
    short_open_tags      : No
    tokenizer            : Yes
    assertions           : Yes
    memory_limit         : 128M
    timezone             :
    token_version        : Php72

php72 :
    configured           : No

php73 :
    configured           : No

php74 :
    configured           : No
```

I've followed those instructions to setup Exakat:
- https://github.com/exakat/gremlin3neo4j2 for getting neo4j with gremlin
- https://exakat.readthedocs.io/en/latest/Installation.html#osx-installation-with-tinkergraph-3-3-3
- Then I had to manually setup the code folder for the project as it is a private one with:
  - `init` command
  - manual checkout of the project into `code` folder

**Comment by exakat** [comment]
This has been fixed in the versions 1.5.x. 
Please, update to the current version 1.5.3, and try only the report : 

 `php exakat.phar report -p xxxx -format Ambassador -v`

**Comment by ravi-kiwitech** [comment]
Issue: Not able to generate report
Using version: 1.6.5
Check below error:

Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : Could not initialize class org.codehaus.groovy.vmplugin.v7.IndyInterface

 ===================  SERVER TRACE  ========================= 
array (
  'stackTrace' => 'java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.IndyInterface
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:330)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:327)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:351)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:341)
	at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:291)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:298)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at org.apache.tinkerpop.gremlin.groovy.loaders.GremlinLoader.load(GremlinLoader.groovy:27)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.<init>(GremlinGroovyScriptEngine.java:252)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngineFactory.getScriptEngine(GremlinGroovyScriptEngineFactory.java:63)
	at org.apache.tinkerpop.gremlin.jsr223.DefaultGremlinScriptEngineManager.createGremlinScriptEngine(DefaultGremlinScriptEngineManager.java:415)
	at org.apache.tinkerpop.gremlin.jsr223.DefaultGremlinScriptEngineManager.getEngineByName(DefaultGremlinScriptEngineManager.java:219)
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.lambda$getEngineByName$0(CachedGremlinScriptEngineManager.java:57)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:57)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:263)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
',
  'exceptions' => 
  array (
    0 => 'java.lang.NoClassDefFoundError',
  ),
)
 ============================================================ 
 
on file phar:///home/kiwitech/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 829

**Comment by rbrisita** [comment]
I get this output:
```
Building report for project prj in "report', with format Ambassador
Can't produce Ambassador format. There are 1 missing rulesets : Inventory.
Reported 0 messages in Ambassador
Processing time : 0.00s
Done
```
Using Mac OS X v10.13.6, PHP v7.3 and exakat:
`Version : 2.0.4 - Build 1016 - Mon, 18 Nov 2019 17:02:22 +0000`
