### ISSUE TITLE
Error during Exakat scan: GC overhead limit exceeded

### ISSUE THREAD

**Issue by kstalega** [exakat/exakat#80]
Hi,

I'm using Ubuntu 16,04. When I'm trying to scan a little bit bigger project i get this error:
```
php exakat.phar project -v -p joomla-3-8-3
Cleaning project
Cleaning project joomla-3-8-3
removing log
removing datastore.sqlite
Removed 1 files
Recreating database
Search for external libraries
Processing files
No files to process. Aborting
Running project 'joomla-3-8-3'
Running the following analysis : Security
Producing the following reports : Owasp
Cleaning DB
stop gremlin server 3.2.x
start gremlin server 3.2.x
started gremlin server
Restarted in 11 rounds
started [5651] in 6,603.01 ms
Running files
Check composer
Searching for files
Found the files.
Check compilation for 72
Check short tag (normal pass)
Check short tag (with directive activated)
Short tag OK
Check config files
+ .appveyor.yml
 + build.xml
 + codeception.yml
 + composer.json
 + composer.lock
 + .php_cs
 + .drone.yml
 + .git
 + .gitignore
 + .github
 + phpunit.xml.dist
 + RoboFile.php
 + .travis.yml
Done
Array
(
    [notCompilable52] => N/C
    [notCompilable53] => N/C
    [notCompilable54] => N/C
    [notCompilable55] => N/C
    [notCompilable56] => N/C
    [notCompilable70] => N/C
    [notCompilable71] => N/C
    [notCompilable72] => 0
    [notCompilable73] => N/C
    [notCompilable74] => N/C
    [php] => 3535
)
Loading with SplitGraphson
Init finalize

Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : GC overhead limit exceeded

 ===================  SERVER TRACE  ========================= 
array (
  'stackTrace' => 'java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.toCharArray(String.java:2899)
	at java.util.zip.ZipCoder.getBytes(ZipCoder.java:78)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:316)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1054)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:105)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:58)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:565)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:458)
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:97)
	at org.neo4j.tinkerpop.api.impl.Neo4jTxImpl.close(Neo4jTxImpl.java:47)
	at org.apache.tinkerpop.gremlin.neo4j.structure.Neo4jGraph$Neo4jTransaction.doCommit(Neo4jGraph.java:336)
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:105)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.lambda$commitAll$2(DefaultGraphManager.java:158)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager$$Lambda$184/206527576.accept(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap$EntrySetView.forEach(ConcurrentHashMap.java:4795)
	at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.commitAll(DefaultGraphManager.java:155)
	at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.attemptCommit(AbstractOpProcessor.java:305)
	at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.handleIterator(AbstractOpProcessor.java:174)
	at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.lambda$evalOpInternal$5(AbstractEvalOpProcessor.java:268)
	at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor$$Lambda$154/876043853.accept(Unknown Source)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:302)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor$$Lambda$81/668955548.call(Unknown Source)
',
  'exceptions' => 
  array (
    0 => 'java.lang.OutOfMemoryError',
  ),
)
 ============================================================ 
 
on file phar:///home/konrad/Documents/exakat/exakat.phar/vendor/brightzone/gremlin-php/src/Connection.php
on line 829
```
What can I do?

**Comment by exakat** [comment]
There isn't enough memory for the graph database to run. 

Before running exakat, set this environnement variable : 
JAVA_OPTIONS=’-Xms1024m -Xmx6096m’;
(Xms is the memory allocation at start, and XMX is the maximum allocation. 6Gb should be good for this project). 

https://exakat.readthedocs.io/en/latest/FAQ.html#java-out-of-memory-error


3535 files is fairly large. I suggest you'd try the installation on a smaller project (for example https://github.com/sculpin/sculpin).

**Comment by kstalega** [comment]
I need to use your tool on big projects, I use machine with more memory and all went ok, thanks a lot!
